version: '3'

services:

  web:
    build: ./web
    container_name: nuxt-ts-docker-env-spike
    tty: true
    stdin_open: true
    ports:
      - "3001:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.nuxt
    command: "yarn run dev:docker"
